// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c17df8f5-e2f5-43a8-a972-54045e81344c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_lLmJ1Wawi",
    "aws_user_pools_web_client_id": "a8nd6mlf93ctg8r6jt9hlho3r"
};


export default awsmobile;
