// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ccbdc1ea-a6cf-461c-8155-10ca9e7233e9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r8wHKr208",
    "aws_user_pools_web_client_id": "7paim42i6c53ap857i9agi0985"
};


export default awsmobile;
